#ifndef COMMON
#define COMMON

#define VIEW_POINT			0x00
#define VIEW_WIRE			0x01
#define VIEW_FLAT			0x02

#define CRTL_LOAD			0x00
#define CRTL_CHANGE			0x01
#define CRTL_TRIANGLE		0x02
#define CRTL_CUBE			0x03
#define CRTL_CIRCLE			0x04
#define CRTL_CYLINDER		0x05
#define CRTL_CONE			0x06
#define CRTL_MODEL			0x07

#define SHAPE_TRIANGLE		0x00
#define SHAPE_CUBE			0x01
#define SHAPE_CIRCLE		0x02
#define SHAPE_CYLINDER		0x03
#define SHAPE_CONE			0x04
#define SHAPE_MODEL			0x05

#define TRANSFORM_NONE      0x51 
#define TRANSFORM_ROTATE    0x52
#define TRANSFORM_SCALE     0x53 
#define TRANSFORM_TRANSLATE 0x54

#define CRTL_BSPLINE_RECURSIVE   0x55
#define CRTL_BSPLINE_DYNAMIC     0x56
#define CRTL_BSPLINE_FORMULA     0x57

#define SHAPE_BSPLINE_RECURSIVE   0x58
#define SHAPE_BSPLINE_DYNAMIC     0x59
#define SHAPE_BSPLINE_FORMULA     0x60
#endif 